# Generated by Django 5.1.3 on 2025-01-02 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_servicio', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(default=False)),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.miembro')),
                ('dia_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='servicios.diaservicio')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('equipo_de_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.equipo')),
            ],
        ),
        migrations.AddField(
            model_name='diaservicio',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_servicio', to='servicios.servicio'),
        ),
    ]
