# Generated by Django 5.1.3 on 2025-01-02 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_rename_presente_asistencia_aseo_asistencia_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaservicio',
            name='observaciones_reunion',
            field=models.TextField(null=True),
        ),
    ]
