# Generated by Django 5.1.3 on 2025-01-02 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_diaservicio_observaciones_reunion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='diaservicio',
            name='merienda',
            field=models.CharField(max_length=50, null=True, verbose_name='Merienda'),
        ),
        migrations.AddField(
            model_name='diaservicio',
            name='numero_de_asistencia',
            field=models.IntegerField(null=True, verbose_name='Numero de Asistencia'),
        ),
        migrations.AddField(
            model_name='diaservicio',
            name='numero_de_bicicletas',
            field=models.IntegerField(null=True, verbose_name='Numero de Bicicletas'),
        ),
        migrations.AddField(
            model_name='diaservicio',
            name='numero_de_carros',
            field=models.IntegerField(null=True, verbose_name='Numero de Carros'),
        ),
        migrations.AddField(
            model_name='diaservicio',
            name='numero_de_meriendas',
            field=models.IntegerField(null=True, verbose_name='Numero de Meriendas Servidas'),
        ),
        migrations.AddField(
            model_name='diaservicio',
            name='numero_de_motos',
            field=models.IntegerField(null=True, verbose_name='Numero de Motos'),
        ),
        migrations.AddField(
            model_name='diaservicio',
            name='numero_de_sillas',
            field=models.IntegerField(null=True, verbose_name='Numero de Sillas'),
        ),
        migrations.AddField(
            model_name='diaservicio',
            name='pastor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servicios.miembro'),
        ),
        migrations.AddField(
            model_name='diaservicio',
            name='tema',
            field=models.CharField(max_length=50, null=True, verbose_name='Tema'),
        ),
        migrations.AddField(
            model_name='diaservicio',
            name='versiculo_base',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='DetalleChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(max_length=100)),
                ('Checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.checklist')),
            ],
        ),
    ]
