# Generated by Django 5.1.3 on 2025-01-02 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_checklist_visita_diaservicio_merienda_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.servicio')),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.miembro', verbose_name='Nombre')),
            ],
        ),
    ]
