# Generated by Django 5.1.3 on 2025-01-02 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0006_aportacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50, verbose_name='descripcion del gasto')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Costo')),
                ('fecha_gasto', models.DateField(verbose_name='Fecha del Gasto')),
                ('Servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.servicio')),
            ],
        ),
    ]
