# Generated by Django 5.1.3 on 2025-01-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0009_producto_movimientoinventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='tipo_movimiento',
            field=models.CharField(choices=[('ING', 'Ingreso'), ('SAL', 'Salida'), ('AJU', 'Ajuste')], default='ING', max_length=3),
        ),
    ]
