# Generated by Django 5.1.3 on 2025-01-02 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0010_movimientoinventario_tipo_movimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='dia_de_servicio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servicios.diaservicio'),
        ),
    ]
