# Generated by Django 5.1.3 on 2025-01-02 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0011_visita_dia_de_servicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anuncio', models.CharField(max_length=300)),
                ('fecha', models.DateField()),
                ('dia_de_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.diaservicio')),
            ],
        ),
    ]
