# Generated by Django 5.1.3 on 2025-01-02 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0013_alter_anuncio_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='direccion',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='miembro',
            name='fecha_de_nacimiento',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='miembro',
            name='primera_visita',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='miembro',
            name='telefono',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
