# Generated by Django 5.1.3 on 2025-01-02 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0015_miembro_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='foto',
            field=models.ImageField(upload_to='media'),
        ),
    ]
