# Generated by Django 5.1.3 on 2025-01-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0017_alter_miembro_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='excusa',
            field=models.BooleanField(default=False),
        ),
    ]
